version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: FleetDb
    ports:
      - "5432:5432"
    networks:
      - mongo-net

  mongo1:
    image: mongo:latest
    container_name: mongo1
    command: ["mongod", "--replSet", "rs0", "--port", "27017", "--bind_ip_all"]
    ports:
      - "27017:27017"
    networks:
      - mongo-net

  mongo2:
    image: mongo:latest
    container_name: mongo2
    command: ["mongod", "--replSet", "rs0", "--port", "27018", "--bind_ip_all"]
    ports:
      - "27018:27018"
    networks:
      - mongo-net

  mongo3:
    image: mongo:latest
    container_name: mongo3
    command: ["mongod", "--replSet", "rs0", "--port", "27019", "--bind_ip_all"]
    ports:
      - "27019:27019"
    networks:
      - mongo-net

networks:
  mongo-net:
    driver: bridge